title: 23.Go函数之错误和异常
date: 2020-04-29
tags: Go
categories: Go语言
layout: post

------

摘要：本节介绍`Go`语言的函数中的错误和异常

<!-- more -->

对于大部分函数而言，永远无法确保能否成功运行。这是因为错误的原因超出了程序员的控制。举个例子，任何进行`I/O`操作的函数都会面临出现错误的可能，只有没有经验的程序员才会相信读写操作不会失败，即使是简单的读写。因此，当本该可信的操作出乎意料的失败后，我们必须弄清楚导致失败的原因。

## 错误

在`Go`中，函数运行失败时会返回错误信息，这些错误信息被认为是一种**预期的值**而非异常（`exception`），这使得`Go`有别于那些将函数运行失败看作是异常的语言

对于那些将运行失败看作是预期结果的函数，它们会返回一个额外的返回值，通常是最后一个，来传递错误信息。如果导致失败的原因只有一个，额外的返回值可以是一个布尔值，通常被命名为`ok`。比如，`cache.Lookup`失败的唯一原因是`key`不存在

```Go
value, ok := cache.Lookup(key)
if !ok {
    // ...cache[key] does not exist…
}
```

通常，导致失败的原因不止一种，尤其是对`I/O`操作而言，用户需要了解更多的错误信息。因此，额外的返回值不再是简单的布尔类型，而是`error`类型。

`error`类型是一个接口类型，可能是`nil`或者`non-nil`

- `nil`：运行成功
- `non-nil`：运行失败

调用`error`的`Error`函数或者输出函数获得字符串类型的错误信息

```Go
fmt.Println(err)
fmt.Printf("%v", err)
```

通常可以使用`fmt.Errorf`函数，格式化错误信息并返回

```go
doc, err := html.Parse(resp.Body)
resp.Body.Close()
if err != nil {
    return nil, fmt.Errorf("parsing %s as HTML: %v", url,err)
}
```

### 错误信息

错误信息经常是以链式组合在一起的，所以错误信息中应避免大写和换行符。最终的错误信息可能很长，我们可以通过类似`grep`的工具处理错误信息

编写错误信息时，我们要确保错误信息对问题细节的描述是详尽的。尤其是要注意错误信息表达的一致性，即相同的函数或同包内的同一组函数返回的错误在构成和处理方式上是相似的

以`OS`包为例，`OS`包确保文件操作（如`os.Open`、`Read`、`Write`、`Close`）返回的每个错误的描述不仅仅包含错误的原因（如无权限，文件目录不存在）也包含**文件名**，这样调用者在构造新的错误信息时无需再添加这些信息

一般而言，被调函数`f(x)`会将调用信息和参数信息作为发生错误时的上下文放在错误信息中并返回给调用者，调用者需要添加一些错误信息中不包含的信息

### 错误处理策略

**1. 传播错误**

适用情况：函数中某个子程序的失败，变成整个函数的失败

```go
resp, err := http.Get(url)
if err != nil{
    return nil, err
}
```

**2.重新尝试**

适用情况：当错误发生时偶然的，或不可预知问题导致时

在重试时，我们需要限制重试的时间间隔或重试的次数，防止无限制的重试

```go
// WaitForServer attempts to contact the server of a URL.
// It tries for one minute using exponential back-off.
// It reports an error if all attempts fail.
func WaitForServer(url string) error {
    const timeout = 1 * time.Minute
    deadline := time.Now().Add(timeout)
    for tries := 0; time.Now().Before(deadline); tries++ {
        _, err := http.Head(url)
        if err == nil {
            return nil // success
        }
        log.Printf("server not responding (%s);retrying…", err)
        time.Sleep(time.Second << uint(tries)) // exponential back-off
    }
    return fmt.Errorf("server %s failed to respond after %s", url, timeout)
}
```

**3.输出错误并结束**

适用情况：如果错误发生后，程序无法继续运行，**仅限在`main`中执行**

```go
// (In function main.)
if err := WaitForServer(url); err != nil {
    fmt.Fprintf(os.Stderr, "Site is down: %v\n", err)
    os.Exit(1)
}
```

输出错误信息`fmt.Fprintf()`并结束`os.Exit()`，可以使用`log.Fatalf`替代

`log.fatalf`：

- 默认在输出的信息之前，添加时间前缀
- 设置`log`的前缀信息屏蔽时间信息，通常前缀信息被设置成命令名

```go
log.SetPrefix("wait: ")
log.SetFlags(0)
if err := WaitForServer(url); err != nil {
    log.Fatalf("Site is down: %v\n", err)
}
```

**4.输出错误**

适用情况：只需要输出错误信息就足够了，不需要中断程序的运行

```Go
if err := Ping(); err != nil {
    log.Printf("ping failed: %v; networking disabled",err) // 自动添加换行符
}
if err := Ping(); err != nil {
    fmt.Fprintf(os.Stderr, "ping failed: %v; networking disabled\n", err)
}
```

**5.忽略错误**

适用情况：不需要关注是否发生了错误

例如：对于临时文件的处理，即使程序执行时因错误导致未完全清理，操作系统也会定期清理

### 使用习惯

在`Go`中，错误处理有一套独特的编码风格

- 检查某个子函数是否失败后，我们通常将处理失败的逻辑代码放在处理成功的代码**之前**

- 如果某个错误会导致函数返回，那么成功时的逻辑代码不应放在`else`语句块中，而应直接放在函数体中

- `Go`中大部分函数的代码结构几乎相同，首先是一系列的初始检查，防止错误发生，之后是函数的实际逻辑

通常情况下，当函数返回错误时`err != nil`，无需对其它返回值进行处理

- 因为执行逻辑不完整，而且在函数中可以没有对其它返回值赋值
- 除文件/网络操作，遇到文件结尾或者网络连接关闭，也需要对读取到的部分数据进行处理

## 异常

在`Go`中，我们通常讲的异常是指`panic`

当`panic`异常发生时，程序会中断执行，并立即执行在该`goroutine`中被延迟的函数，并输出异常日志

`panic`一般用于严重错误，如程序内部的逻辑不一致，我们应该谨慎使用

可以在代码中显式的执行`panic`函数，触发异常，但我们通常使用`err`错误机制即可达到相同的效果

```go
func Reset(x *Buffer) {
    if x == nil {
        panic("x is nil") 
    }
    x.elements = nil
}
```

### 异常日志

包括`panic value`和函数调用的堆栈跟踪信息

- `panic value`：通常是某种错误信息
- 函数调用堆栈跟踪信息：提供足够的定位错误和诊断的依据

```go
panic: runtime error: integer divide by zero
main.f(0)
src/gopl.io/ch5/defer1/defer.go:14
main.f(1)
src/gopl.io/ch5/defer1/defer.go:16
main.f(2)
src/gopl.io/ch5/defer1/defer.go:16
main.f(3)
src/gopl.io/ch5/defer1/defer.go:16
main.main()
src/gopl.io/ch5/defer1/defer.go:10
```

## 捕获

当发生`panic`异常时，我们需要从异常中恢复，而不是选择让程序崩溃。这就需要将`panic`异常当作普通的错误，并附加额外信息提醒用户报告此错误。

这就需要在`defer`函数中调用内置函数`recover`，会使程序从`panic`中恢复，返回`panic value`。导致`panic`异常的函数会正常返回

```go
func Parse(input string) (s *Syntax, err error) {
    defer func() {
        if p := recover(); p != nil {
            err = fmt.Errorf("internal error: %v", p)
        }
    }()
    // ...parser...
}
```

- `Parse`函数中没有发生`panic`异常，`recover`的返回值为`nil`
- `Parse`函数中发生`panic`异常，`recover`返回`non-nil`，记录`panic value`

通常情况下，不加区分的恢复所有`panic`异常是不可取的。尤其是调用第三方包的函数时发生`panic`异常，有可能导致变量的状态异常。记住：慎重处理非自己代码中的`panic`异常

推荐的做法是：将`panic value`设置成特殊类型。在`recover`时对`panic value`进行检查，如果发现`panic value`是特殊类型，就将这个`panic`作为`errror`处理，如果不是，则按照正常的`panic`进行处理

```Go
// soleTitle returns the text of the first non-empty title element
// in doc, and an error if there was not exactly one.
func soleTitle(doc *html.Node) (title string, err error) {
    type bailout struct{} // 特殊类型的panic value
    defer func() {
        switch p := recover(); p {
        case nil:       // no panic
        case bailout{}: // "expected" panic
            err = fmt.Errorf("multiple title elements")
        default:
            panic(p) // unexpected panic; carry on panicking
        }
    }() // 不要忘了调用
    // Bail out of recursion if we find more than one nonempty title.
    forEachNode(doc, func(n *html.Node) {
        if n.Type == html.ElementNode && n.Data == "title" &&
            n.FirstChild != nil {
            if title != "" {
                panic(bailout{}) // multiple titleelements
            }
            title = n.FirstChild.Data
        }
    }, nil)
    if title == "" {
        return "", fmt.Errorf("no title element")
    }
    return title, nil
}
```

其实，本例中触发`panic`违反了触发异常的原则，这里应该使用`error`而不是`panic`

### 习题5.19

```go
package main

import "fmt"

func do(x int) (result int) {
	defer func() {
		if r := recover(); r != nil {
			result = r.(int)
		}
	}()
	panic(x) // 相当于 return语句
}

func main() {
	fmt.Println(do(0))

}

// 返回 "0"
```





